openapi: 3.0.0
info:
  description: Documentation for timetracker backend
  version: "1.0.0"
  title: Timetracker docs

servers:
  - url: http://localhost:5000/api
    description: Local development
  - url: https://ha-timetracker-backend.herokuapp.com/api
    description: Production API

paths:
  /users:
    get:
      operationId: users.list_all
      tags:
        - Users
      summary: Get all users
      responses:
        '200':
          description: List all users
          content:
            application/json:
              schema:
                required:
                  - status
                  - data
                type: object
                properties: 
                  status:
                    type: integer
                    enum: [200]
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
    post:
      operationId: users.add
      tags:
        - Users
      summary: Add a user
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserInput'
      responses:
        '201':
          description: The new user was successfully created
          content:
            application/json:
              schema:
                required:
                  - status
                  - data
                type: object
                properties:
                  status:
                    type: integer
                    enum: [201]
                  data:
                    $ref: '#/components/schemas/User'            
        '400':
          $ref: '#/components/responses/InputError'
  /users/{userid}:
    get:
      operationId: users.get
      tags:
        - Users
      summary: Get a user
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: User that was found
          content:
            application/json:
              schema:
                required:
                  - status
                  - data
                properties:
                  status:
                    type: integer
                    enum: [200]
                  data:
                    $ref: '#/components/schemas/User'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      operationId: users.update
      tags:
        - Users
      summary: Update a user
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: The user that was updated
          content:
            application/json:
              schema:
                required:
                  - status
                  - data
                properties:
                  status:
                    type: integer
                    enum: [200]
                  data:
                    $ref: '#/components/schemas/User'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      operationId: users.remove
      tags:
        - Users
      summary: Remove a user
      description: Remove a user with specified ID
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: User was removed
          content:
            application/json:
              schema:
                required:
                  - status
                properties: 
                  status:
                    type: integer
                    enum: [200]
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  /users/{userid}/clockings:
    get:
      operationId: clockings.list_user_clockings
      tags:
        - Clockings
      summary: Get all clockings from a user, sorted in descending order
      parameters:
        - $ref: '#/components/parameters/UserId'
        - name: limit
          in: query
          description: Optional parameter to limit number of returns
          schema:
            type: integer
        - name: since
          in: query
          description: Optional parameter to limit since what datetime clockings should be included
          schema:
            type: string    
            format: date-time
        - name: to
          in: query
          description: Optional parameter to limit to what datetime clockings should be included
          schema:
            type: string    
            format: date-time
      responses:
        '200':
          description: Clockings
          content:
            application/json:
              schema:
                required:
                  - status
                  - data
                properties:
                  status:
                    type: integer
                    enum: [200]
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Clocking'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      operationId: clockings.add
      tags:
        - Clockings
      summary: Adds a clocking
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClockingInput'
      responses:
        '201':
          description: Clocking was created
          content:
            application/json:
              schema:
                required:
                  - status
                  - data
                properties:
                  status:
                    type: integer
                    enum: [201]
                  data:
                    $ref: '#/components/schemas/Clocking'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/InputError'
 
  /users/{userid}/clockings/{clockingid}:
    delete:
      operationId: clockings.remove_clocking
      description: Removes a clocking
      tags:
        - Clockings
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/ClockingId'
      responses:
        '200':
          description: Clocking was removed
          content:
            application/json:
              schema:
                required:
                  - status
                properties: 
                  status:
                    type: integer
                    enum: [200]
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /users/{userid}/password:
    put:
      operationId: users.update_password
      tags:
        - Users
      summary: Update user password
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: True
        content:
          application/json:
            schema:
              properties:
                password:
                  type: string
                  format: password
                newPassword:
                  type: string
                  format: password
      responses:
        '200':
          $ref: '#/components/responses/EmptyOk'
        '401':
          $ref: '#/components/responses/NotAuthorized'          
        '404':
          $ref: '#/components/responses/NotFound'
  /auth/check:
    get:
      operationId: auth.check
      tags:
        - Authentication
      summary: Dummy endpoint without data for authentication check
      responses:
        '200':
          $ref: '#/components/responses/EmptyOk'
        '401':
          $ref: '#/components/responses/NotAuthorized'
  /auth/login:
    post:
      operationId: auth.login
      tags:
        - Authentication
      summary: Logs in
      requestBody:
        required: True
        content:
          application/json:
            schema:
              properties:
                password:
                  type: string
                  format: password
                e-mail:
                  type: string
                  format: email
                mfacode:
                  type: number
              required:
                - password
                - e-mail
      security: []
      responses:
        '200':
          description: Response with token
          headers:
            Set-Cookie:
              schema:
                type: string
          content:
            application/json:
              schema:
                required:
                  - status
                  - data
                  - userid
                properties:
                  status:
                    type: integer
                    enum: [200]
                  data:
                    type: object
                    properties:
                      session:
                        type: string
                      userid:
                        type: number
        '403':
          description: Response to request 2fa authentication if useraccount requires it
          content:
            application/json:
              schema:
                required:
                  - request
                  - status
                properties:
                  status:
                    type: integer
                    enum: [403]
                  detail:
                    type: string
                    enum: ["2fa"]
        '401':
          $ref: '#/components/responses/NotAuthorized'          

  /auth/logout:
    post:
      operationId: auth.logout
      tags:
        - Authentication
      summary: Logs out
      requestBody:
        required: True
        content:
          application/json:
            schema:
              properties:
                session:
                  type: string
      security: []
      responses:
        '200':
          description: User is logged out
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session=ABC123; Max-Age=-1
          content:
            application/json:
              schema:
                required:
                  - status
                  - data
                properties:
                  status:
                    type: integer
                    enum: [200]
                  data:
                    type: object

security:
  - cookieAuth: []

components:
  schemas:
    User:
      required:
        - id
        - name
        - email
      properties:
        id: 
          type: number
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john.doe@email.com
    NewUserInput:
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: john.doe@email.com
        password:
          type: string
          format: password
    UserInput:
      properties:
        name:
          type: string
        email:
          type: string
    Error:
      required:
        - message
      properties:
        message:
          type: string
    DefaultError:
      required:
        - detail
        - status
        - title
      properties:
        detail:
          type: string
        status:
          type: integer
          enum: [400, 401, 404]
        title:
          type: string
        type:
          type: string
    Clocking:
      required:
        - id
        - direction
        - userid
        - datetime
      properties:
        id:
          type: integer
        direction:
          type: string
          enum: [in, out]
        userid:
          type: integer
        datetime:
          type: string
          format: date-time
    ClockingInput:
      required:
        - direction
      properties:
        direction:
          type: string
          enum: [in, out]
        datetime:
          type: string
          format: date-time
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultError'
    InputError:
      description: Request failed due to input error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultError'
    ServerError:
      description: Request failed on the server
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultError'
    NotAuthorized:
      description: Requester is not authorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultError'
    EmptyOk:
      description: Response with just a 200-status code
      content:
        application/json:
          schema:
            required:
              - status
            properties:
              status:
                type: integer
                enum: [200]
  parameters:
    UserId:
      name: userid
      in: path
      description: Userid
      required: True
      schema:
        type: integer
    ClockingId:
      name: clockingid
      in: path
      description: ID of clocking
      required: True
      schema:
        type: integer
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
      x-apikeyInfoFunc: auth.isValidSession